// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Scope = /* module */[];

var Patch = /* module */[];

var Overload = /* module */[];

exports.Scope = Scope;
exports.Patch = Patch;
exports.Overload = Overload;
/* No side effect */
